;METADATA=(Diff=true, UseCommands=true)
[CommonSettings]
SourcePath=Content/Localization/Game
DestinationPath=../../TestLanguages
NativeCulture=en
CulturesToGenerate=en
CulturesToGenerate=fr-FR
ManifestName=Game.manifest
ArchiveName=Game.archive
DialogueScriptName=GameDialogue.csv

[GatherTextStep0]
CommandletClass=ExportDialogueScript

